name: Test on BDK-FFI Latest Commit

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-bdk-python-test ]

permissions: {}

jobs:
  test-bdk-ffi-latest:
    name: "Build and run offline tests on Manylinux 2.28 x86_64 (Python 3.14) against the latest commit on bdk-ffi"
    runs-on: ubuntu-24.04
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
      env:
        PLAT: manylinux_2_28_x86_64
        PYBIN: "/opt/python/cp314-cp314/bin"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: "Configure Git safe directory"
        run: git config --global --add safe.directory /__w/bdk-python/bdk-python

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7

      - name: "Set up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Update bdk-ffi submodule to latest"
        run: |
          cd ./bdk-ffi/ \
          && git fetch origin \
          && git checkout master \
          && git pull origin master \
          && echo "Testing commit: $(git log -1 --pretty=format:'%h %s (author: %cn)')"

      - name: "Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: "Generate bdk.py and binaries"
        run: bash ./scripts/generate-linux.sh --skip-submodule-update

      - name: "Build wheel"
        run: UV_PYTHON=${PYBIN}/python uv build --wheel --config-setting=--build-option=--plat-name=manylinux_2_28_x86_64 --verbose

      - name: "Install wheel"
        run: uv pip install --system --python ${PYBIN}/python ./dist/*.whl

      - name: "Run tests"
        run: ${PYBIN}/python -m unittest discover --start "./tests/" --pattern "test_offline_*.py" --verbose
